### ISSUE TITLE
Feature Request: Include the org or user from the repo slug in the local path

### ISSUE THREAD

**Issue by acourtneybrown** [chrisgrieser/gitfred#5]
### Feature Requested

When you clone a repo using the `gh` verb in Alfred, the resulting clone gets placed at the root of the `Cloning:` directory.  This layout leads to potential name collisions and prevents cloning multiple forks from GitHub using this Alfred workflow.

I could see either adding a checkbox to the configuration panel to `Include repo owner in path` or allowing a `{owner}` substitution in the `Cloning:` textbox.  Then the workflow command would just need to ensure that the `owner` dir existed under the `Cloning:` dir when performing the clone.

### Relevant Screenshot

For example:

![image](https://github.com/user-attachments/assets/183d98d0-508e-48b0-94e4-ea67ef64e799)

then using `gh github/gitignore` followed by `^+Enter` would clone the repo into `~/github.com/github/gitignore`.

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
I have solved the problem differently, the workflow now automatically renames repos of the same name to prepend the owner name, so that forks are distinguishable.

Available in the Alfred Gallery in 1-2 days, or directly by downloading the latest release here: https://github.com/chrisgrieser/gitfred/releases/download/1.6.0/gitfred.alfredworkflow
